EasyPaymentGatewayService:
    Db:
        LogsConnString:
            settings-key: EasyPaymentGatewayService-LogsConnString
            types:
              - AzureTableStorage
    Merchant:
        MerchantId:
            settings-key: EasyPaymentGatewayService-MerchantId
            types: [Tag]
        MerchantPassword:
            settings-key: EasyPaymentGatewayService-MerchantPassword
            types: [Tag]
        ProductId:
            settings-key: EasyPaymentGatewayService-ProductId
            types: [Tag]
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
PersonalDataServiceClient:
    ApiKey: 
        settings-key: PersonalDataApiKey
    ServiceUri:
        settings-key: PersonalDataServiceUrl

