EasyPaymentGatewayService:
    Db:
        LogsConnString:
            settings-key: EasyPaymentGatewayService-LogsConnString
            types:
              - AzureTableStorage
    Merchant:
        MerchantId:
            settings-key: EasyPaymentGatewayService-MerchantId
            types: [Tag]
        MerchantPassword:
            settings-key: EasyPaymentGatewayService-MerchantPassword
            types: [Tag]
        ProductId:
            settings-key: EasyPaymentGatewayService-ProductId
            types: [Tag]
    EpgProvider:
        CheckoutUrl:
            settings-key: EasyPaymentGatewayService-CheckoutUrl
            types: [Tag]
    WebHook:
        StatusUrl:
            settings-key: EasyPaymentGatewayService-WebHookStatusUrl
            types: [Tag]
    Redirect:
        OkUrl:
            settings-key: EasyPaymentGatewayService-OkUrl
            types: [Tag]
        ErrorUrl:
            settings-key: EasyPaymentGatewayService-ErrorUrl
            types: [Tag]
        CancelUrl:
            settings-key: EasyPaymentGatewayService-CancelUrl
            types: [Tag]
    SourceClientId:
        settings-key: EasyPaymentGatewayService-SourceClientId
        types: [Tag]
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
PersonalDataServiceClient:
    ApiKey: 
        settings-key: PersonalDataApiKey
    ServiceUri:
        settings-key: PersonalDataServiceUrl